### ISSUE TITLE
type stream from STDIN

### ISSUE THREAD

**Issue by inutano** [suecharo/tataki#2]

**Comment by fmaccha** [comment]
design memo

- read from STDIN when `-` is specified as an argument.
- write `--num-records * 4 + max(20, (number of lines starting with '#' or '@')` lines into a temporary file.
- since the temporary file does not contain the entirety of STDIN,
    - conflict with the `--tidy` option and terminate the run with an error.
    - conflict with cwl extension mode and terminate the run with an error.

**Comment by fmaccha** [comment]
design memo

- read from STDIN when `-` is specified as an argument.
- write `--num-records * 4 + max(20, (number of lines starting with '#' or '@')` lines into a temporary file.
- since the temporary file does not contain the entirety of STDIN,
    - conflict with the `--tidy` option and terminate the run with an error.
    - conflict with cwl extension mode and terminate the run with an error.
